name: Slack Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch commit information
        id: commits
        run: |
          commits=$(git log --format="%h - %an: %s" -n 3)
          echo "::set-output name=commits::$commits"

      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          # Parse commit information
          commits="${{ steps.commits.outputs.commits }}"
          message="New commits pushed to main branch:\n\n"

          # Get the hash of the current commit and its parent
          current_commit=$(git rev-parse HEAD)
          parent_commit=$(git rev-parse HEAD^)
          # Filter out changes in the src directory
          changes=$(git diff --name-only HEAD~1 HEAD | grep "^src/")
          
          # Loop through each changed file
          while IFS= read -r file; do
              # Get the diff of the file
              diff=$(git show --stat --pretty="format:" $parent_commit..$current_commit -- "$file")
              # Append the file name and diff to the message
              message+="*Changes in $file:*\n$diff\n\n"
          done <<< "$changes"
          
          # Send message to Slack
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$message\"}" $SLACK_WEBHOOK_URL
